//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NZJobFInder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int JobId { get; set; }
        public string jobTitle { get; set; }
        public string jobRespon { get; set; }
        public string jobSalary { get; set; }
        public string jobLocation { get; set; }
        public string jobContactNum { get; set; }
        public string jobContactEmail { get; set; }
        public int fk_eID { get; set; }
    
        public virtual Employer Employer { get; set; }
    }
}
